- id: '1657652516061'
  alias: Relay 1 on
  description: ''
  trigger:
  - platform: mqtt
    topic: moisture/sensor1
  condition:
  - condition: state
    entity_id: sensor.sensor_1
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: relays/relay1
      payload: 'on'
  - service: mqtt.publish
    data:
      payload: 'on'
      topic: pump
  mode: single
- id: '1657653702931'
  alias: Relay 2 on
  description: ''
  trigger:
  - platform: mqtt
    topic: moisture/sensor2
  condition:
  - condition: state
    entity_id: sensor.sensor_2
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: relays/relay2
      payload: 'on'
  - service: mqtt.publish
    data:
      topic: pump
      payload: 'on'
  mode: single
- id: '1658156821771'
  alias: Pump off when all relays are off
  description: ''
  trigger:
  - platform: mqtt
    topic: relays/relay1
    id: trigger1
  - platform: mqtt
    topic: relays/relay2
    id: trigger2
  - platform: mqtt
    topic: relays/relay3
    id: trigger3
  condition:
  - condition: state
    entity_id: sensor.relay_1
    state: 'off'
  - condition: state
    entity_id: sensor.relay_2
    state: 'off'
  - condition: state
    entity_id: sensor.relay_3
    state: 'off'
  action:
  - service: mqtt.publish
    data:
      topic: pump
      retain: true
      payload: 'off'
  mode: single
- id: '1658159041928'
  alias: Relay 3 on
  description: ''
  trigger:
  - platform: mqtt
    topic: moisture/sensor3
  condition:
  - condition: state
    entity_id: sensor.sensor_3
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: relays/relay3
      payload: 'on'
  - service: mqtt.publish
    data:
      topic: pump
      payload: 'on'
  mode: single
- id: '1661270224448'
  alias: Relay 1 off
  description: ''
  trigger:
  - platform: mqtt
    topic: moisture/sensor1
  condition:
  - condition: state
    entity_id: sensor.sensor_1
    state: 'off'
  action:
  - service: mqtt.publish
    data:
      topic: relays/relay1
      payload: 'off'
  mode: single
- id: '1661271286596'
  alias: Relay 2 off
  description: ''
  trigger:
  - platform: mqtt
    topic: moisture/sensor2
  condition:
  - condition: state
    state: 'off'
    entity_id: sensor.sensor_2
  action:
  - service: mqtt.publish
    data:
      topic: relays/relay2
      payload: 'off'
  mode: single
- id: '1661271348729'
  alias: Relay 3 off
  description: ''
  trigger:
  - platform: mqtt
    topic: moisture/sensor3
  condition:
  - condition: state
    entity_id: sensor.sensor_3
    state: 'off'
  action:
  - service: mqtt.publish
    data:
      topic: relays/relay3
      payload: 'off'
  mode: single
