- id: '1657652516061'
  alias: Relay 1
  description: ''
  trigger:
  - platform: mqtt
    topic: moisture/sensor1
  condition:
  - condition: numeric_state
    entity_id: sensor.sensor_1
    below: '80'
  action:
  - service: mqtt.publish
    data:
      topic: relays/relay1
      payload: 'on'
      retain: true
  - service: mqtt.publish
    data:
      payload: 'on'
      retain: true
      topic: pump
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: relays/relay1
      retain: true
      payload: 'off'
  mode: single
- id: '1657653702931'
  alias: Relay 2
  description: ''
  trigger:
  - platform: mqtt
    topic: moisture/sensor2
  condition:
  - condition: numeric_state
    entity_id: sensor.sensor_2
    below: '80'
  action:
  - service: mqtt.publish
    data:
      topic: relays/relay2
      payload: 'on'
      retain: true
  - service: mqtt.publish
    data:
      topic: pump
      payload: 'on'
      retain: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: relays/relay2
      payload: 'off'
      retain: true
  mode: single
- id: '1658156821771'
  alias: Pump off when all relays are off
  description: ''
  trigger:
  - platform: mqtt
    topic: relays/relay1
    id: trigger1
  - platform: mqtt
    topic: relays/relay2
    id: trigger2
  - platform: mqtt
    topic: relays/relay3
    id: trigger3
  condition:
  - condition: state
    entity_id: sensor.relay_1
    state: 'off'
  - condition: state
    entity_id: sensor.relay_2
    state: 'off'
  - condition: state
    entity_id: sensor.relay_3
    state: 'off'
  action:
  - service: mqtt.publish
    data:
      topic: pump
      retain: true
      payload: 'off'
  mode: single
- id: '1658159041928'
  alias: Relay 3
  description: ''
  trigger:
  - platform: mqtt
    topic: moisture/sensor3
  condition:
  - condition: numeric_state
    entity_id: sensor.sensor_3
    below: '80'
  action:
  - service: mqtt.publish
    data:
      topic: relays/relay3
      payload: 'on'
      retain: true
  - service: mqtt.publish
    data:
      topic: pump
      payload: 'on'
      retain: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: relays/relay3
      payload: 'off'
      retain: true
  mode: single
