mqtt:
  sensor:
    - name: "Sensor 1"
      unique_id: "Sensor 1"
      state_topic: "moisture/sensor1"
    - name: "Sensor 2"
      unique_id: "Sensor 2"
      state_topic: "moisture/sensor2"
    - name: "Sensor 3"
      unique_id: "Sensor 3"
      state_topic: "moisture/sensor3"
    - name: "Temperature"
      unique_id: "Temperature"
      state_topic: "temperature"
      unit_of_measurement: "°C"
      device_class: "temperature"
    - name: "Relay 1"
      unique_id: "Relay 1"
      state_topic: "relays/relay1"
    - name: "Relay 2"
      unique_id: "Relay 2"
      state_topic: "relays/relay2"
    - name: "Relay 3"
      unique_id: "Relay 3"
      state_topic: "relays/relay3"
    - name: "Pump"
      unique_id: "Pump"
      state_topic: "pump"